name: Terraform Workflow

on:
  push:
    branches:
      - dev
      - uat
      - main
  pull_request:
    branches:
      - dev
      - uat
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Verifica o repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # Configura o Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # Configura as Credenciais da AWS com base na branch
    - name: Configure AWS Credentials
      run: |
        if [ "${{ github.ref_name }}" == "dev" ]; then
          echo "Configuring AWS for DEV"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_DEV }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}" >> $GITHUB_ENV
        elif [ "${{ github.ref_name }}" == "uat" ]; then
          echo "Configuring AWS for UAT"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_UAT }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_UAT }}" >> $GITHUB_ENV
        elif [ "${{ github.ref_name }}" == "main" ]; then
          echo "Configuring AWS for MAIN"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_MAIN }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_MAIN }}" >> $GITHUB_ENV
        fi  

    # Seleciona o arquivo .tfvars de acordo com a branch
    - name: Determine .tfvars file based on branch
      run: |
        echo "tfvars_file=${{ github.ref_name }}.tfvars" >> $GITHUB_ENV
        
    # Executa o Terraform Init
    - name: Terraform Init
      run: terraform init

    # Executa o Terraform Plan
    - name: Terraform Plan
      run: terraform plan -var-file="${{ env.tfvars_file }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}

    # Executa o Terraform Apply
    - name: Terraform Apply -var-file="${{ env.tfvars_file }}"
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
